services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: nemmest
      POSTGRES_USER: nemmest
      POSTGRES_PASSWORD: nemmest
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
